large = ['OUTER', 'TOPS', 'BOTTOMS', 'SKIRTS', 'ONEPIECE', 'SHOES']
medium = [
    'HOODED_ZIP_UP', 'BLOUSON', 'BLAZER', 'CARDIGAN', 'COAT', 'WIND_BREAKER', 'PADDING',
    'TOPS_LONG', 'TOPS_SHORT', 'LESS',
    'BOTTOMS_LONG', 'BOTTOMS_SHORT',
    'SKIRTS_LONG', 'MIDI', 'MINI'
]
small = [
    'HOODED_ZIP_UP', 'BLOUSON', 'CARDIGAN', 'BLAZER', 'SINGLE', 'TRENCH', 'WIND_BREAKER', 'LONG', 'SHORT',

    'TOPS_LONG_NEAT', 'TOPS_LONG_HOODED', 'TOPS_LONG_SWEAT', 'TOPS_LONG_SHIRTS', 'TOPS_LONG_T_SHIRTS', 'TOPS_LONG_SPORTS',
    'TOPS_SHORT_POLO', 'TOPS_SHORT_SHIRTS', 'TOPS_SHORT_SWEAT', 'TOPS_SHORT_T_SHIRTS', 'TOPS_SHORT_SPORTS',
    'TOPS_LESS_LESS',

    'BOTTOMS_LONG_DENIM', 'BOTTOMS_LONG_SLACKS', 'BOTTOMS_LONG_SWEAT', 'BOTTOMS_LONG_CARGO', 'BOTTOMS_LONG_LEGGINGS', 'BOTTOMS_LONG_COTTON', 'BOTTOMS_LONG_SPORTS',
    'BOTTOMS_SHORT_DENIM', 'BOTTOMS_SHORT_SWEAT', 'BOTTOMS_SHORT_COTTON', 'BOTTOMS_SHORT_SPORTS',

    'SKIRTS_LONG_LAB', 'SKIRTS_LONG_FLARE', 'SKIRTS_LONG_MERMAID',
    'MIDI_H', 'MIDI_A', 'MIDI_PLEATS', 'MIDI_FLARE', 'MIDI_K',
    'MINI_H', 'MINI_A', 'MINI_LAB', 'MINI_FLARE'
]
fit = ['SKINNY', 'SLIM', 'REGULAR', 'LOOSE', 'OVER']
gender = ['MALE', 'FEMALE', 'UNISEX']
style = ['FORMAL', 'MINIMALISTIC', 'CASUAL', 'STREET', 'SPORTS']